kind = "web"
previewPath = "/"
title = "Soundwave"
version = "1.0.0"
id = "artifacts/soundwave"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24251

[services.development]
run = "pnpm --filter @workspace/soundwave run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/soundwave", "run", "build" ]
serve = "static"
publicDir = "artifacts/soundwave/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24251"
BASE_PATH = "/"
